# Generated by Django 5.2.1 on 2025-08-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatics',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image16',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image17',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='informatics',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image16',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image17',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image16',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image17',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
    ]
