# Generated by Django 5.2.1 on 2025-09-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_informatics_image1_informatics_image10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='imaget',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='math',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
