# Generated by Django 5.2.1 on 2025-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_math_imaget_math_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='imaget',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
