# Generated by Django 5.2.1 on 2025-09-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_math_imaget'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='image21',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image22',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image23',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image24',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='image25',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='math',
            name='ob21',
            field=models.TextField(default=1, verbose_name='Объяснение 21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='ob22',
            field=models.TextField(default=1, verbose_name='Объяснение 22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='ob23',
            field=models.TextField(default=1, verbose_name='Объяснение 23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='ob24',
            field=models.TextField(default=1, verbose_name='Объяснение 24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='ob25',
            field=models.TextField(default=1, verbose_name='Объяснение 25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='otv21',
            field=models.TextField(default=1, verbose_name='Ответ 21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='otv22',
            field=models.TextField(default=1, verbose_name='Ответ 22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='otv23',
            field=models.TextField(default=1, verbose_name='Ответ 23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='otv24',
            field=models.TextField(default=1, verbose_name='Ответ 24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='otv25',
            field=models.TextField(default=1, verbose_name='Ответ 25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='vopr21',
            field=models.TextField(default=1, verbose_name='Вопрос 21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='vopr22',
            field=models.TextField(default=1, verbose_name='Вопрос 22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='vopr23',
            field=models.TextField(default=1, verbose_name='Вопрос 23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='vopr24',
            field=models.TextField(default=1, verbose_name='Вопрос 24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='math',
            name='vopr25',
            field=models.TextField(default=1, verbose_name='Вопрос 25'),
            preserve_default=False,
        ),
    ]
