# Generated by Django 5.2.1 on 2025-10-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_math_image21_math_image22_math_image23_math_image24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics',
            name='image21',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='image22',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AddField(
            model_name='physics',
            name='ob21',
            field=models.TextField(default=1, verbose_name='Объяснение 21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='ob22',
            field=models.TextField(default=1, verbose_name='Объяснение 22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='otv21',
            field=models.TextField(default=1, verbose_name='Ответ 21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='otv22',
            field=models.TextField(default=1, verbose_name='Ответ 22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='vopr21',
            field=models.TextField(default=1, verbose_name='Вопрос 21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='vopr22',
            field=models.TextField(default=1, verbose_name='Вопрос 22'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='math',
            name='otv24',
            field=models.TextField(blank=True, verbose_name='Ответ 24'),
        ),
    ]
