# Generated by Django 5.2.1 on 2025-10-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_physics_image21_physics_image22_physics_ob21_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informatics',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='image20',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='ob17',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='ob18',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='ob19',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='ob20',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='otv17',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='otv18',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='otv19',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='otv20',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='vopr17',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='vopr18',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='vopr19',
        ),
        migrations.RemoveField(
            model_name='informatics',
            name='vopr20',
        ),
    ]
