# Generated by Django 5.2.1 on 2025-11-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_informatics_image17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics',
            name='url17',
            field=models.TextField(default=1, verbose_name='Ссылка 17'),
            preserve_default=False,
        ),
    ]
