# Generated by Django 5.2.1 on 2025-11-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_physics_url17'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatics',
            name='url13',
            field=models.TextField(default=1, verbose_name='Ссылка 13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informatics',
            name='url14',
            field=models.TextField(default=1, verbose_name='Ссылка 14'),
            preserve_default=False,
        ),
    ]
