# Generated by Django 5.2.1 on 2025-11-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_informatics_url13_informatics_url14'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informatics',
            old_name='url13',
            new_name='myurl13',
        ),
        migrations.RenameField(
            model_name='informatics',
            old_name='url14',
            new_name='myurl14',
        ),
        migrations.RenameField(
            model_name='physics',
            old_name='url17',
            new_name='myurl17',
        ),
    ]
